#!/usr/bin/with-contenv bash
# ==============================================================================
# Timmo Hass.io Add-ons: Home Panel
# Starts server to serve the api
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

hass.log.info "Run API.."

# shellcheck disable=SC2164
cd /opt/api

local DB_PATH
local CONFIG_PATH
local SSL_PATH_CERT
local SSL_PATH_KEY

DB_PATH=/config/home-panel.db
CONFIG_PATH=/config/$(hass.config.get 'config_file')

if hass.config.true 'ssl'; then
    SSL_PATH_CERT="/ssl/$(hass.config.get 'certfile')"
    SSL_PATH_KEY="/ssl/$(hass.config.get 'keyfile')"
fi

exec node index.js
