#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Home Panel
# Starts server to serve the API
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

hass.log.info "Run API.."

cd /opt/api \
    || hass.die "Could not change into API directory"

LOG_LEVEL=$(hass.config.get 'log_level')
DB_PATH=/config/home-panel.db
CONFIG_PATH=/config/$(hass.config.get 'config_file')

if hass.config.true 'ssl'; then
    SSL_PATH_CERT="/ssl/$(hass.config.get 'certfile')"
    SSL_PATH_KEY="/ssl/$(hass.config.get 'keyfile')"
fi

export LOG_LEVEL
export DB_PATH
export CONFIG_PATH
export SSL_PATH_CERT
export SSL_PATH_KEY

exec node index.js
